apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  schemaVersion: v1.0.0
  name: numbers-java-sdk
  description: This SDK is no longer supported by Bandwidth and has been deprecated. Please use the SDK found here instead: https://github.com/Bandwidth/java-bandwidth-iris
  annotations:
    github.com/project-slug: Bandwidth/numbers-java-sdk
    organization: BW
    costCenter: Development - Software Infra
spec:
  type: Library
  owner: github/band-swi
  lifecycle: Available
